configs_to_do:
- prova
configs_to_avoid: []
groups_to_do:
- prova_small_5pat_4cu_2op
groups_to_avoid: []
instances_to_do:
- inst_00
instances_to_avoid: []
structure_type: slim-fat
solver_name: glpk
core_type: generalist
post_pruning_irreducibility: false
core_patient_expansion: false
core_service_expansion: false
core_operator_expansion: false
core_day_expansion: false
max_single_core_expansion: 32
use_true_cache: false
use_cache_selection_model: false
max_iteration: 100000000
total_time_limit: 900
early_stop_optimum_approximation_percentage: 1.0
master:
    time_limit: 300
    memory_limit: 16
    additional_info:
    - minimize_hospital_accesses
    - use_optimality_cuts
subproblem:
    time_limit: 30
    memory_limit: 16
    additional_info:
    - use_redundant_operator_cut
cache:
    time_limit: 60
    memory_limit: 16
core_pruning:
    time_limit: 30
    memory_limit: 16
    additional_info:
    - use_redundant_operator_cut
core_expansion:
    time_limit: 30
    memory_limit: 16
subsumption:
    time_limit: 30
    memory_limit: 16
