groups:
  test:
    groups_to_do:
    - all
  prova:
    groups_to_do:
    - all
    instances_to_do:
    - all
    solver_name: glpk
    total_time_limit: 900
    master:
      time_limit: 300
base:
  configs_to_do:
  - prova
  configs_to_avoid: []
  groups_to_do:
  - all
  groups_to_avoid: []
  instances_to_do:
  - all
  instances_to_avoid: []
  structure_type: slim-fat
  solver_name: gurobi
  core_type: generalist
  post_pruning_irreducibility: false
  core_patient_expansion: false
  core_service_expansion: false
  core_operator_expansion: false
  core_day_expansion: false
  max_single_core_expansion: 32
  use_true_cache: false
  use_cache_selection_model: false
  max_iteration: 100000000
  total_time_limit: 7200
  early_stop_optimum_approximation_percentage: 0.0
  master:
    time_limit: 600
    memory_limit: 16
    additional_info:
    - minimize_hospital_accesses
    - use_optimality_cuts
  subproblem:
    time_limit: 30
    memory_limit: 16
    additional_info:
    - use_redundant_operator_cut
  cache:
    time_limit: 60
    memory_limit: 16
  core_pruning:
    time_limit: 30
    memory_limit: 16
    additional_info:
    - use_redundant_operator_cut
  core_expansion:
    time_limit: 30
    memory_limit: 16
  subsumption:
    time_limit: 30
    memory_limit: 16
