plots_to_do:
- experiment_group_comparison
experiment_group_comparison_config_order:
- generalist
- basic
- reduced
- pruned
- irreducible_pruned
- pruned_pat_expansion
- pruned_pat_srv_expansion
- monolithic
experiment_group_comparison_config_aliases:
  generalist: day_unsat
  basic: singleton
  reduced: reduced
  pruned: pruned
  irreducible_pruned: irred_pruned
  pruned_pat_expansion: PRU+PAT_EXP
  pruned_pat_srv_expansion: PRU+PAT_SRV_EXP
  monolithic: MONO
